# Generated by Django 5.1.6 on 2025-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
        ('dashboard', '0002_subscription'),
    ]

    operations = [
    ]
