# Generated by Django 5.1.6 on 2025-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_merge_0002_profile_0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tracker_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
