# Generated by Django 5.1.6 on 2025-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_subscription_tracker_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
